name: unit-tests
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  run:
    container: golang:1.15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Generate coverage report
        run: |
          go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          flags: unittests
          fail_ci_if_error: true